### ISSUE TITLE
FOSDEM 2018 Open Source Design organisation

### ISSUE THREAD

**Issue by ei8fdb** [opensourcedesign/events#64]
I am copying @evalica's great list from this year's preparation thread, and replicating it here. Yes, I'm being presumptuous, but hea...I'm positive!

---------

## 2018 FOSDEM guidelines/tasks

- [x] Submit [**proposal**](https://submission.fosdem.org/devroom.php) for Developer Room on Fosdem.org | [example](https://github.com/opensourcedesign/events/issues/41#issuecomment-241662291) | [Deadline](https://submission.fosdem.org/devroom.php): 20 September
- [ ] Submit proposal for Stand on Fosdem.org #52 | [Deadline](https://www.fosdem.org/2018/news/2017-09-03-call-for-participation/): 3 November
- [x] See accepted developer rooms **announcement** on Fosdem.org | [example](https://INSERT-LINK) | Deadline: 2 October
- [x] Create Fosdem 2018 [**event**](https://INSERT-GITHUB-LINK) on opensourcedesign.net | [example](http://opensourcedesign.net/events/2016/01/30/fosdem-2016) | Deadline: 16 October (Create event as soon as devroom is accepted)
- [x] Create Fosdem 2018 Call for Participation [**article**](https://INSERT-GITHIB-LINK) on opensourcedesign.net | [example](http://opensourcedesign.net/events/2016/01/30/opensourcedesign-fosdem-2016) |  Deadline: 16 October (Or as soon as devroom is accepted)
  - [ ] Fix the dates for the track when they are announced
- [x] Manage the Fosdem 2018 [Call for Participation](https://INSERT-GITHIB-LINK) step on Fosdem.org | Deadline: 16 October (or earlier)
- [x] **Promote** the Call for Participation on Twitter and [OS](https://github.com/opensourcedesign/events/issues/22#issuecomment-158799947) [mailinglists](https://github.com/opensourcedesign/events/issues/22#issuecomment-159428347) | [example](https://twitter.com/belenpena/status/658997539757268992) | Deadline: 16 October (Or as soon as devroom is accepted)
- [ ] [**Brainstorm**](https://github.com/opensourcedesign/events/issues/45) on talks | [example](https://github.com/opensourcedesign/events/issues/30) | Deadline: 15 December (Or as soon as devroom is accepted)
- [x] Create the session proposals **review spreadsheet** | [example](https://docs.google.com/spreadsheets/d/1bj906jUu57e5fy6TokLcGv_GUL6CmgRbe6SEsTipy7Y/edit#gid=0) | Deadline: 15 December (Or as soon as devroom is accepted)
- [ ] Send **review mail** to community members on mailinglist | [mail](https://github.com/opensourcedesign/events/issues/22#issuecomment-163378167): Session proposals for review - Open Source Design devroom | Deadline:  15 December (or earlier)
- [ ] The acceptance / rejection **notifications** to speakers via pentabarf | Deadline: 15 December (or earlier)
- [ ] Publish developer rooms **complete schedules** on Fosdem.org | [example](https://archive.fosdem.org/2016/schedule/track/open_source_design/) | Deadline: 15 December (or earlier)
- [ ] Create **promotional** materials (stickers, banners) for opensourcedesign #43 | Deadline: INSERT-DATE
- [ ] Organize the open source design **dinner** #62 | Deadline: INSERT-DATE
- [ ] Handle the devroom logistics **videobox** | [example](https://github.com/FOSDEM/video) | Deadline: INSERT_DATE
- [ ] **Cover** the event on Twitter | [example](https://twitter.com/opensrcdesign/status/693359800277671936) | Deadline: 4-5 Feb
- [ ] Open Source Design Devroom sessions **presenter** | Deadline: 4-5 Feb
- [ ] Open Source Design Dinner + **picture** | Deadline: 3-5 Feb
- [ ] Open Source Design Devroom **picture** | [example](https://twitter.com/evalica/status/693493767844818945) | Deadline: 4-5 Feb
- [ ] Review the **videos** recording start/end times for the talks in order to be published
- [ ] Create FOSDEM 2018 **slides** folder on opensourcedesign Github [example](https://github.com/opensourcedesign/talks/tree/master/fosdem%202017) | Deadline: 1 Mar
- [ ] Submit talks **slides** on opensourcedesign GitHub| [example](https://github.com/opensourcedesign/talks/tree/26fc7394837f1bfd7435ffbbe213c1f325729769/fosdem%202018) | Deadline: 1 Mar
- [ ] Write **post event** article on opensourcedesign.net | Deadline: 1 Mar
- [ ] Provide a link to the video recordings | [example](http://video.fosdem.org/2016/aw1120/STATUS.TXT) | Deadline: 31 Jul

**Comment by evalica** [comment]
According to the [CFP](https://www.fosdem.org/2018/news/2017-09-03-call-for-participation/) and the [DevRoom](https://submission.fosdem.org/devroom.php) page the DEADLINE for DevRooms is **20 September**. 
- Do we [want](https://twitter.com/Xaviju/status/899594631125639168) to participate in 2018? (It will be our fourth room in a row)
-- Who wants to handle the organization? We need at least 2 contact for coordinators. 
--- (I can help, but if there are other volunteers we should switch to make sure everything is nice and balanced) 
- Do we also want a [stand](https://github.com/opensourcedesign/events/issues/52)?
-- Who wants to handle this? 

WDYT? @belenbarrospena @ei8fdb @jancborchardt @victoria-bondarchuk @Xaviju @bnvk @elioqoshi @simonv3 @jdittrich @gillisig @danilapellicani

**Comment by jancborchardt** [comment]
We should definitely participate again and not break our streak. :) I can help in the room as usual and also at a booth, but also need to make sure I’m available for the Nextcloud booth. And it would be great to get people involved more who didn’t organize the devroom so far. :)

A stand in addition would be quite nice also. If it’s close to the Nextcloud stand, it would be no problem for me to switch around. The question is if we have the people to be there and what we exactly want to do there:
- Simply advertise our collective
- Have small discussions
- Maybe quick design reviews?

**Comment by belenbarrospena** [comment]
+1 for a new devroom

About the stand, I really would like to have a design clinic this year. That will give the stand some purpose, since we have very little swag and materials about the group.

I am happy to take on the logistics and happy to help with the devroom process as well.

Soooo exciting! :)

**Comment by evalica** [comment]
Does someone know if the booth is for both days or just 1? It would be nice to have the booth in a different day than the DevRoom.

**Comment by victoria-bondarchuk** [comment]
We should have a room for sure! Now when I'm in Europe, I would like to contribute as well. Please count on me!

**Comment by belenbarrospena** [comment]
@evalica I believe booths must be the 2 days. I agree it would be easier to do it just during the non-devroom day, but on the other hand we might have nice "synergies" between both if they are happening at the same time, i.e people coming out of sessions and dropping by the design clinic to get some advice on their project. 

We just need to make sure we are well organised so that we split ourselves between devroom and booth and everybody gets to do a bit of both.

**Comment by PanderMusubi** [comment]
May I suggest a clinic in Inkscape Open Symbols?

**Comment by belenbarrospena** [comment]
@PanderMusubi Sure, anything. The way a clinic works is you drop by the desk, you bring up a topic you want to discuss with a designer, and you talk about it together. It's not supposed to solve the whole problem, just give high-level advice and some guidance on how to proceed.

If you were to come to me with the Inskcape Open Symbols, for example, I would probably look at them more from a usability perspective, and would recommend some quick user testing for any non-standard icons :)

**Comment by evalica** [comment]
We can discuss/vote on the logo format in https://github.com/opensourcedesign/events/issues/43

**Comment by victoria-bondarchuk** [comment]
I would like to volunteer to be a main contact for the proposal this year (if anyone else wants, please speak up!) We need 2 contact people anyway, so if you feel like it lets do it together. 
I aim to send proposal until Monday 11th, reusing previous [submission examples](https://github.com/opensourcedesign/events/issues/41#issuecomment-241662291).  I will post a draft here by tomorrow. 
I'm also under impression that @elioqoshi wanted to take care of stand submission.

**Comment by victoria-bondarchuk** [comment]
Here is slightly changed proposal draft from the last year application. Added remark about room accessibility. 

Any comments, correction? 
@belenbarrospena @ei8fdb @jancborchardt @Xaviju @bnvk @elioqoshi @simonv3 @jdittrich @gillisig @danilapellicani 

**Project details** 

**Title of devroom:**
Open Source Design

**Elaborate description of proposed devroom (including possible topics):**
After three successful devrooms in FOSDEM 2015, 2016 and 2017, we would like to repeat the experience also this year. Since the beginning of our Open Source Design community (http://opensourcedesign.net/) we promoted several initiatives, like having a "jobs board" where FOSS projects looking for design contributors can connect with available designers. FOSDEM helped us having a place to meet yearly face to face, talk about the projects/ideas/challenges we faced over the year and we hope to have a healthy number of proposals submitted and great attendance this year too.
The goal of this devroom is to showcase design work done within free and open source projects, and strengthen the connections between designers involved in FOSS. We mean "design" in a broad sense, and we include within that term typography, graphic design, interaction design, user experience and design research activities.

Possible topics include:

FOSS design tools
Design techniques and deliverables
Design - engineering collaboration approaches
User engagement and design research activities
Project case studies

After receiving several requests, we will probably dedicate an hour to project pitches, so that projects looking for design contributions can introduce themselves and establish contact with designers eager to help.

**Why does it fit FOSDEM?**
FOSS projects bring in particular challenges that affect almost every aspect of design. Techniques and approaches used in closed software settings must be re-purposed and adapted to FOSS. This is hard to do on your own. We hope that sharing experiences across projects and communities will help establish a set of practices that are effective, flexible and transferable across FOSS projects.

During last years the devroom also proved to be a great way of connecting designers with FOSS projects looking for design contributors. Having a devroom again next year will increase our chances to expand the community and will give us the opportunity to spread the word between developers regarding how and where to get design help for their projects.

**Preferred slot:**
Full day

**Contact information**

**Primary contact**
First name: Victoria
Last name: Bondarchuk
E-mail: victoria.bondarchuk@gmail.com
Submitter's affinity to the topic of the devroom:
UX researcher and part of the Open Source Design community (opensourcedesign.net) since  2016.

**Secondary contact**
First name: 
Last name: 
E-mail: 
= Additional information =

Relevant URLs:
https://discourse.opensourcedesign.net/
https://github.com/opensourcedesign
http://opensourcedesign.net/
https://twitter.com/opensrcdesign

**Special requirements:**
Room with access for wheelchairs, or who have access needs.

**Comment by belenbarrospena** [comment]
@victoria-bondarchuk Thanks for putting together the proposal. This looks good to me. The only suggestion is, in the goals of the devroom, you could add "to increase awareness of user-centered design among the free and open source community"

About the secondary contact, I'd be happy to be added in

First name: Belen
Last name: Barros Pena
E-mail: belenbarrospena@gmail.com

@elioqoshi Unless you say otherwise, I will put together the stand proposal this weekend. I think this year is the right year for our design clinic :)

Cheers

Belén

**Comment by jancborchardt** [comment]
@victoria-bondarchuk @belenbarrospena aaawesome, thank you so much! :) Looks great

**Comment by elioqoshi** [comment]
@victoria-bondarchuk looks great to me, thanks!

@belenbarrospena just saw it before replying to the stand thread. Please feel free to go ahead and let me know if I can help.

**Comment by victoria-bondarchuk** [comment]
The proposal has been submitted, accepted developer rooms will be announced on 2 October! Fingers crossed!

**Comment by victoria-bondarchuk** [comment]
Hurray! Our proposal was accepted! I will follow the checklist and make announcements on the website and call for participation in a few days!

**Comment by victoria-bondarchuk** [comment]
Hi everyone! 

We have posted call for participation here: http://opensourcedesign.net/events/2018/02/04/opensourcedesign-fosdem-2018 

Please promote! 
@evalica @jancborchardt @simonv3 @jdittrich @belenbarrospena @dimitrieh @cameralibre @bnvk @ei8fdb @elioqoshi @blackkaaht @pdurbin @cameralibre @digitigrafo @pkruithofjr @h-nes @HeikoTietze @Kriesse @gillisig @Xaviju @gsambrotta @andreasn @qwazix @eppfel @whitef0x0 @bbalazs

**Comment by belenbarrospena** [comment]
Wonderful! Don't forget to send it to the devroom organisers mailing list so that they know is out :)

**Comment by belenbarrospena** [comment]
LOL. Just saw the message on the mailing list. You are waaaaaay ahead of me :D

**Comment by ei8fdb** [comment]
Well done to everyone. I've been a bit quiet for a bit. See you all in Brussels for 2018.

**Comment by victoria-bondarchuk** [comment]
@ei8fdb looking forward to seeing you, btw would you consider to give a talk? @belenbarrospena would be great to hear about your academic research? Apply for a talk!

**Comment by belenbarrospena** [comment]
My goal is, like every year, not to present! :) Having said that, if we are
short on proposals, I will try and think of something.

Cheers,

Belén

**Comment by ei8fdb** [comment]
@victoria-bondarchuk I can try. If I can get organised!

**Comment by dimitrieh** [comment]
I have to see if I can be there, will have facts on that soon. No tickets needed right?

**Comment by victoria-bondarchuk** [comment]
@dimitrieh  yes, no tickets are needed. Would be really great if someone from GitLab would give a talk on open design process or user research. Open Source Design devroom at FOSDEM usually has the most engaged audience!
CfP is open until 1 of December: https://discourse.opensourcedesign.net/t/call-for-participation-open-source-design-devroom-at-fosdem-2018/363

**Comment by dimitrieh** [comment]
cool stuff, when I know more, will come back to this!

**Comment by elioqoshi** [comment]
@dimitrieh would be great to see you there again!

@victoria-bondarchuk and co: will we extend the deadline? 1st December seems pretty early.
I am writing a blog post and promote this a bit on our Ura channels in the meantime

**Comment by victoria-bondarchuk** [comment]
@elioqoshi as far as I remember we did extend it last year, but not for long, we have to complete schedule by 15 of December anyway. So far we have 3 submissions on the system and one suggestion from the members on the forum. Please share the link once you write a post!

**Comment by jancborchardt** [comment]
I'd say to keep the deadline for now and only extend it once we reach it. Cause usually people hand in submissions during the last days anyway, so we shouldn't extend too early. ;)

**Comment by dimitrieh** [comment]
I'll be attending Fosdem 2018 and have submitted a talk for GitLab. A colleague of mine from UX research has submitted a talk for UX research as well! :)

**Comment by digitigrafo** [comment]
I also proposed for the OSD room: 

**Case Studies of Discussion Platforms**
:)

**Comment by victoria-bondarchuk** [comment]
Hi everyone, 
I'm suggesting to extend the deadline till 7th of December. What do you think? We will have more than a week to vote on submissions.

**Comment by jancborchardt** [comment]
@victoria-bondarchuk yup, seems ok, especially as now many submitted so close to the deadline. :) Let's announce the extension tomorrow?
Also, how many proposals do we have in? Last year we had roughly 16 sessions and we should think about only starting at 10:00 (having maybe 30mins welcome session before) cause usually before it's empty.

**Comment by victoria-bondarchuk** [comment]
## Proposals Status

Today is CfP deadline. Thanks everyone, who promoted the event and submitted talks! 
We have 22 proposals, see spreadsheet [here](https://docs.google.com/spreadsheets/d/14o3tHnAO19Q8WPBdJs7PaolMX09oG_4msDUcYW3-s7o/edit?usp=sharing). I reused the same format, proposed by @evalica, as well as copied last year voting rules below. 

**VOTE DEADLINE**
December 13

**HOW TO VOTE**
You will have 12 votes per user. You vote by adding your name to a column (N+) and add a '1' to the row/talk you want to accept. You shouldn't vote for your own sessions (you can add an N/A). You can add additional comments in your column.

@evalica @jancborchardt @simonv3 @jdittrich @belenbarrospena @dimitrieh @ei8fdb @elioqoshi  @pdurbin  @HeikoTietze @Xaviju  @andreasn 

## Organizational details ##

### How many sessions should we accept this year? ###
As we learned last year, starting at 9 a.m. might be a bit early, and as @jancborchardt suggested let's start at 10:00. That would give us 14 slots of 20 minutes (+10 for questions and preparations) in 10:00-17:00 timeframe.  I assume "Open Source Design collective" and "Pitch your project" events are accepted by default, so we have to choose 12 talks. 

### My submission is missing
If you cannot find your submission on the list, please contact me. 
@belenbarrospena if you have some time, would be great if you could check if I copied everything correctly from penta. 

### Diner
Shall we plan for the community dinner on Friday before FOSDEM? 

### Monthly call
What do you think if we start our monthly call practice again to make sure everything is ready for FOSDEM? See https://github.com/opensourcedesign/events/issues/49

**Comment by belenbarrospena** [comment]
@victoria-bondarchuk had a quick look to the content in penta and the spreadsheet, and everything looks good to me.

Everybody! Peer review is important for content quality, so please read through the proposals and cast your votes!! :)

**Comment by victoria-bondarchuk** [comment]
## Proposals Status

[12 submissions were accepted](https://docs.google.com/spreadsheets/d/14o3tHnAO19Q8WPBdJs7PaolMX09oG_4msDUcYW3-s7o/edit#gid=91128727), based on the [vote results](https://docs.google.com/spreadsheets/d/14o3tHnAO19Q8WPBdJs7PaolMX09oG_4msDUcYW3-s7o/edit#gid=905844715). However, 2 people couldn't confirm their participation, so additional two talks were accepted to fill the schedule.  Currently, all talks are confirmed except one, where the speaker needs to make sure she will be able to obtain a visa. We have to submit final schedule until 24th of December if this speaker wouldn't confirm her participation we will have to go with next most voted submission on the list. I really hope she will confirm her participation, and more people outside of EU could join the event. 

I will be sending rejection letters by the end of the week. ;/

Current schedule you can find here: https://fosdem.org/2018/schedule/track/open_source_design/ 

Thank you, everyone, for help, I think we are almost done!

**Comment by tessgadwa** [comment]
Ok, well, you'll be hearing from me on #9 -- the pitch portion of the
event. http://lotuspetalarchitecture.com wants your attention!

Looking forward to being at FOSDEM this year.

Tess Gadwa

**Comment by evalica** [comment]
Thanks everyone for your involvement, especially @victoria-bondarchuk, you rocked! 
See you next year! :)

**Comment by jancborchardt** [comment]
Copied over the planning again for a possible FOSDEM 2019 into the forum :) https://discourse.opensourcedesign.net/t/fosdem-2019-open-source-design-organization/692
